# Generated by Django 5.0.2 on 2024-03-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_alter_customuser_user_permissions_pointofinterest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointofinterest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
