# Generated by Django 5.0.2 on 2024-03-25 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_alter_pointofinterest_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointofinterest',
            options={},
        ),
    ]
