# Generated by Django 5.0.2 on 2024-03-25 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_pointofinterest_migration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointofinterest',
            options={'managed': True},
        ),
        migrations.AlterModelTable('PointOfInterest', 'maps_pointofinterest'),
    ]
