# Generated by Django 5.0.2 on 2024-03-26 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_alter_pointofinterest_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pointofinterest',
            table=None,
        ),
    ]
