# Generated by Django 5.0.2 on 2024-03-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_remove_pointofinterest_added_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofinterest',
            name='layer',
            field=models.CharField(default='points-view', max_length=100),
        ),
    ]
