# Generated by Django 5.0.2 on 2024-04-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0007_pointofinterest_layer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointofinterest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='layer',
            field=models.CharField(default='tutorial:points_view', max_length=100),
        ),
    ]
