# Generated by Django 5.0.2 on 2024-03-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPXData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gpx_file', models.FileField(upload_to='gpx_files/')),
            ],
        ),
    ]
